### PR TITLE
Update Jenkinsfile in mor1kx

### PR DESCRIPTION
**Pull request by Nancy-Chauhan**
Updated the version of librecores/librecores-ci docker image. In reference to #83

### CODE REVIEW

**Comment by stffrdhrn** [comment]
In July 5th @olofk added jtag_vpi r3 which the librecores-ci build is picking up and failing on.  This is likely a problem with that new version. 

1. Quick fix, we can update the core file to require r2
2. Longer fix, fix the root cause

**Comment by stffrdhrn** [comment]
In July 5th @olofk added jtag_vpi r3 which the librecores-ci build is picking up and failing on.  This is likely a problem with that new version. 

1. Quick fix, we can update the core file to require r2
2. Longer fix, fix the root cause

**Comment by Nancy-Chauhan** [comment]
Thanks, @stffrdhrn. I am working to fix this

**Comment by stffrdhrn** [comment]
I can't merge when there is a failure. It sould be fixed now. Can you try the build again?  If it's green I can merge

**Comment by Nancy-Chauhan** [comment]
@stffrdhrn Actually @oleg-nenashev and I tried running it but there was a disk space problem, not enough for parallel OpenRISC runs and Docker on the same host.https://github.com/librecores/librecores-ci-jenkins-server/issues/64, which will be fixed most probably next week

**Comment by Nancy-Chauhan** [comment]
@stffrdhrn  Now I rebuild it!  Works fine now

**Pull request merged**
