### PR TITLE
Fixups: Implement sign extension + Fixes

### PR DESCRIPTION
**Pull request by stffrdhrn**
Working on fixing up some of the test cases in or1k-tests.  I found l.ext* instructions were never implemented.  I implemented it using case because I thought its easy to read like that.  But if others have suggestions let me know.

### CODE REVIEW

**Comment by stffrdhrn** [comment]
This looks to fix  #53

**Comment by stffrdhrn** [comment]
I added a commit the this PR to fix #48 too.

**Comment by olofk** [comment]
The core file and the shorter fixes look fine to me. I'm afraid I don't know the code well enough to give a proper review of the ext stuff, but it looks like it does the job. Only thing I'm wondering is if this will put more logic in the alu_result_o path even when FEATURE_EXT is disabled? Please take a look at that, but I'm happy to see these patches merged anway

**Comment by stffrdhrn** [comment]
Thanks for the review. It's a good point in the extra logic on alu_result_o. I tried to model the other optional features which I assumed would be optimized out when disabled.   I will check what I can see in the netlist, I might find I need to fix other optional functions as well.

**Comment by stffrdhrn** [comment]
Thank you,  I made the change to clean up `decode_op_ext_o` logic as suggested by Andrey and this should also help to remove the logic from `alu_result_o` when extension is disabled.  But I am away from my desktop and done know how to check the synthesis results from the command line.

Also, one strange thing, I am trying to test the mor1kx build with de0_nano-multicore.  But Its failing to fit.  It seems something has come into mor1kx or another core which is causing us to go over the resource limit now.  I am looking into it.  Once its fixed I will merge this.

Also, I added one more commit to pull the BRANCH PREDICTION parameter up to the mor1kx top.

**Comment by stffrdhrn** [comment]
I updated the fix for #66 as discussed with Philipp, I am hoping switching to 2 clocks will work for xilinx, it works for altera.

**Comment by stffrdhrn** [comment]
I am merging this.  `or1k-test` results are looking OK.

```
Running or1k-alignillegalinsn                               PASS
Running or1k-backtoback_jmp                                 PASS
Running or1k-basic                                          PASS
Running or1k-cmov                                           PASS
Running or1k-cy                                             FAIL  - failing as mor1kx doesn't support multiply carry
Running or1k-dsx                                            PASS
Running or1k-dsxinsn                                        PASS
Running or1k-ext                                            PASS
Running or1k-ffl1                                           PASS
Running or1k-icache                                         PASS
Running or1k-illegalinsn                                    PASS
Running or1k-illegalinsndelayslot                           PASS
Running or1k-insnfetchalign                                 PASS
Running or1k-insnfetcherror                                 PASS
Running or1k-intloop                                        PASS
Running or1k-intmulticycle                                  PASS
Running or1k-intsyscall                                     PASS
Running or1k-inttickloop                                    PASS
Running or1k-jmp                                            PASS
Running or1k-jr                                             PASS
Running or1k-lsu                                            PASS
Running or1k-lsualign                                       PASS
Running or1k-lsualigndelayslot                              PASS
Running or1k-lsuerror                                       PASS
Running or1k-lsuerrordelayslot                              PASS
Running or1k-lwjr                                           PASS
Running or1k-msync                                          PASS
Running or1k-mul-basic                                      PASS
Running or1k-ov                                             PASS
Running or1k-regjmp                                         PASS
Running or1k-rfe                                            PASS
Running or1k-sf                                             PASS
Running or1k-sfbf                                           PASS
Running or1k-shiftopts                                      PASS
Running or1k-shortbranch                                    PASS
Running or1k-shortjump                                      PASS
Running or1k-systemcall                                     PASS
Running or1k-tickloop                                       PASS
Running or1k-tickrfforward                                  PASS
Running or1k-ticksyscall                                    PASS
Running or1k-timer                                          PASS
Running or1k-trap                                           PASS
Running or1k-trapdelayslot                                  PASS
Results                                                     Total:  43  FAIL:   1
```

Creating issue for multiply carry limitation.

**Comment by juliusbaxter** [comment]
This all look good to me. Nice work folks!

**Pull request merged**
