### PR TITLE
Refactoring CI to use librecores-ci-openrisc docker image

### PR DESCRIPTION
**Pull request by Nancy-Chauhan**
This PR resolves the issue of installing the or1k-tests again and again for every Job by using the librecores-ci-openrisc docker image https://github.com/librecores/docker-images/tree/master/librecores-ci-openrisc 
CC @stffrdhrn @oleg-nenashev

### CODE REVIEW

**Comment by Nancy-Chauhan** [comment]
@stffrdhrn @oleg-nenashev does it look fine ?

**Comment by stffrdhrn** [comment]
Can you update README docs to link to librecores-ci-openrisc?

**Comment by stffrdhrn** [comment]
Why is part of the build failing?

**Comment by oleg-nenashev** [comment]
The updated Jenkinsfile doe not get applied to the build, because @Nancy-Chauhan is not a trusted user. I temporarily relaxed the permissions to retest the patch

**Comment by Nancy-Chauhan** [comment]
@stffrdhrn @oleg-nenashev I have added documentation

**Pull request merged**
